"""
Main entry point for BizGenesis.
"""
import sys
import asyncio
import time
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List

from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown
from rich.progress import Progress

from src.agents.market import MarketResearcher
from src.agents.product import ProductManager
from src.agents.marketing import ContentStrategist
from src.agents.seo import SEOExpert
from src.agents.designer import ChiefDesigner
from src.agents.base import BaseAgent
from src.agents.business import BusinessModeler
from src.agents.finance import FinancePlanner
from src.agents.risk import RiskAnalyst

console = Console()


async def run_agent_async(agent: BaseAgent, context: Dict[str, Any]) -> Dict[str, Any]:
    """Run a single agent asynchronously."""
    return await agent.run_async(context)


async def run_agents_parallel(agents: List[BaseAgent], context: Dict[str, Any]) -> Dict[str, Any]:
    """
    Run multiple agents in parallel where possible.
    
    Agents that don't depend on each other's output can run concurrently.
    For this project, we run them sequentially as each depends on previous context.
    """
    for agent in agents:
        context = await run_agent_async(agent, context)
    return context


def run_agents_sequential(agents: List[BaseAgent], context: Dict[str, Any]) -> Dict[str, Any]:
    """Run agents sequentially (traditional approach)."""
    for agent in agents:
        context = agent.run(context)
    return context


def save_to_markdown(context: Dict[str, Any], industry: str) -> Path:
    """Save generated content to a markdown file."""
    # Create output directory
    output_dir = Path(__file__).parent.parent / "output"
    output_dir.mkdir(exist_ok=True)
    
    # Generate filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_industry = industry.replace("/", "_").replace(" ", "_")[:20]
    filename = f"{safe_industry}_{timestamp}.md"
    filepath = output_dir / filename
    
    # Build markdown content
    md_content = f"""# 🚀 创业方案: {industry}

生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## 📊 市场定位

{context.get('market_analysis', '暂无')}

---

## 📦 产品定义

{context.get('product_plan', '暂无')}

---

## 💰 商业模式

{context.get('business_model', '暂无')}

---

## 📈 财务规划

{context.get('finance_plan', '暂无')}

---

## ⚠️ 风险评估

{context.get('risk_analysis', '暂无')}

---

## 🎨 品牌设计

{context.get('design_strategy', '暂无')}

---

## 🎬 流量脚本

{context.get('marketing_script', '暂无')}

---

## 🔍 SEO 策略

{context.get('seo_strategy', '暂无')}

---

*Generated by BizGenesis AI 创业辅助系统*
"""
    
    # Write to file
    filepath.write_text(md_content, encoding='utf-8')
    return filepath

def main():
    console.print(Panel.fit("🚀 BizGenesis - AI 创业辅助系统", style="bold magenta"))
    
    # Get user input
    industry = console.input("[bold green]请输入你想尝试的创业领域/关键词 (例如: 袜子/露营/猫粮): [/]")
    if not industry:
        console.print("[red]输入不能为空！[/]")
        sys.exit()

    context: Dict[str, Any] = {"industry": industry}
    
    # Initialize agents
    agents: List[BaseAgent] = [
        MarketResearcher(),
        ProductManager(),
        BusinessModeler(),
        FinancePlanner(),
        RiskAnalyst(),
        ChiefDesigner(),
        ContentStrategist(),
        SEOExpert()
    ]

    # Run with progress
    with Progress() as progress:
        task = progress.add_task("[cyan]AI 团队正在协同工作...", total=len(agents))
        
        for agent in agents:
            agent_name = agent.__class__.__name__
            progress.update(task, description=f"[cyan]正在执行: {agent_name}")
            
            context = agent.run(context)
            progress.advance(task)
            time.sleep(0.5)

    # Display results
    console.print("\n")
    console.rule("[bold yellow]🎉 创业方案生成完毕[/]")
    
    panels = [
        ("📊 市场定位", "market_analysis", "blue", "Step 1: Market"),
        ("📦 产品定义", "product_plan", "green", "Step 2: Product"),
        ("💰 商业模式", "business_model", "cyan", "Step 3: Business"),
        ("📈 财务规划", "finance_plan", "cyan", "Step 4: Finance"),
        ("⚠️ 风险评估", "risk_analysis", "red", "Step 5: Risk"),
        ("🎨 品牌设计", "design_strategy", "magenta", "Step 6: Design"),
        ("🎬 流量脚本", "marketing_script", "red", "Step 7: Content"),
        ("🔍 SEO 策略", "seo_strategy", "yellow", "Step 8: SEO"),
    ]
    
    for emoji_title, key, style, panel_title in panels:
        content = context.get(key, "")
        if content:
            console.print(
                Panel(Markdown(f"# {emoji_title}\n{content}"), 
                      title=panel_title, 
                      border_style=style)
            )

    # Save to markdown file
    filepath = save_to_markdown(context, industry)
    console.print(Panel(f"💾 方案已保存到: [bold green]{filepath}[/]", style="bold blue"))

    console.print(Panel("💡 Pro Tip: 复制 'Midjourney Prompt' 去生成你的第一个 Logo 吧！", style="italic grey50"))


async def main_async():
    """Async version of main for parallel execution."""
    console.print(Panel.fit("🚀 BizGenesis - AI 创业辅助系统", style="bold magenta"))
    
    industry = console.input("[bold green]请输入你想尝试的创业领域/关键词: [/]")
    if not industry:
        console.print("[red]输入不能为空！[/]")
        return

    context: Dict[str, Any] = {"industry": industry}
    
    agents: List[BaseAgent] = [
        MarketResearcher(),
        ProductManager(),
        BusinessModeler(),
        FinancePlanner(),
        RiskAnalyst(),
        ChiefDesigner(),
        ContentStrategist(),
        SEOExpert()
    ]

    # Run with async support
    context = await run_agents_parallel(agents, context)

    # Display results (same as sync version)
    console.print("\n")
    console.rule("[bold yellow]🎉 创业方案生成完毕[/]")
    
    # ... display logic here ...


if __name__ == "__main__":
    # Use synchronous main by default
    main()
    # For async: asyncio.run(main_async())
